# Numpy

## Numpy is used to do all the mathematical operations on python. Therby named after Numerical Python (Num Py)

In [52]:
import numpy as np

In [53]:
l=[1,2,3,4,5]

In [57]:
a=np.array(l)
a

array([1, 2, 3, 4, 5])

In [58]:
b=np.asarray(l)
b

array([1, 2, 3, 4, 5])

In [59]:
c=np.asanyarray(b)
c

array([1, 2, 3, 4, 5])

In [60]:
d=[[1,2,3],[4,5,6],[7,8,9]]

In [62]:
e=np.array(d)
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a.shape

(5,)

In [64]:
a.size

5

In [65]:
a.ndim

1

In [66]:
e.shape

(3, 3)

In [67]:
e.size

9

In [68]:
e.ndim

2

In [69]:
type(a),type(e)

(numpy.ndarray, numpy.ndarray)

In [71]:
a.dtype

dtype('int64')

In [72]:
e.dtype

dtype('int64')

In [73]:
f=[1,2,3]
g=np.matrix(f)
g

matrix([[1, 2, 3]])

In [74]:
np.asanyarray(g)

matrix([[1, 2, 3]])

In [75]:
np.fromfunction(lambda i,j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
iters=[i*i for i in range(11)]

In [80]:
np.fromiter(iters,float)

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [81]:
np.fromstring("12 4 43 66 3 563 3  57  6 4 323 5",sep=" ")

/tmp/ipykernel_102/474489934.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("hsh shhns hs s an abd adjb",sep=" ")


array([], dtype=float64)

In [85]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.linspace(-22,3,10)

array([-22.        , -19.22222222, -16.44444444, -13.66666667,
       -10.88888889,  -8.11111111,  -5.33333333,  -2.55555556,
         0.22222222,   3.        ])

In [92]:
np.logspace(1,5,15)

array([1.00000000e+01, 1.93069773e+01, 3.72759372e+01, 7.19685673e+01,
       1.38949549e+02, 2.68269580e+02, 5.17947468e+02, 1.00000000e+03,
       1.93069773e+03, 3.72759372e+03, 7.19685673e+03, 1.38949549e+04,
       2.68269580e+04, 5.17947468e+04, 1.00000000e+05])

In [93]:
np.random.randint(1,5,(2,3))

array([[4, 4, 2],
       [3, 3, 4]])

In [95]:
np.random.rand(1,15)

array([[0.08367301, 0.78343311, 0.71139339, 0.93965412, 0.71495561,
        0.48044144, 0.24588983, 0.72485972, 0.65323588, 0.64618872,
        0.89762457, 0.78926811, 0.57523792, 0.12947843, 0.41921687]])

In [97]:
np.random.randn(1,11)

array([[-0.66640135,  1.11057402,  0.27165799, -0.24538106,  0.41967993,
         0.14674209,  0.65105344,  2.19521151, -0.25737895,  0.2709739 ,
         1.04114527]])

In [98]:
np.random.randint(2,4)

2

In [99]:
a=np.random.randint(1,5,(2,3))
b=np.random.randint(1,5,(2,3))

In [100]:
a

array([[2, 3, 2],
       [4, 3, 1]])

In [101]:
b

array([[1, 3, 4],
       [1, 1, 4]])

In [102]:
a+b

array([[3, 6, 6],
       [5, 4, 5]])

In [103]:
a+5

array([[7, 8, 7],
       [9, 8, 6]])

In [104]:
a*b

array([[2, 9, 8],
       [4, 3, 4]])

In [105]:
a-b

array([[ 1,  0, -2],
       [ 3,  2, -3]])

In [106]:
a/b

array([[2.  , 1.  , 0.5 ],
       [4.  , 3.  , 0.25]])

In [108]:
a

array([[2, 3, 2],
       [4, 3, 1]])

In [109]:
b

array([[1, 3, 4],
       [1, 1, 4]])

In [112]:
a/0

/tmp/ipykernel_102/4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf],
       [inf, inf, inf]])

In [116]:
a=a.T

In [117]:
a

array([[2, 4],
       [3, 3],
       [2, 1]])

In [118]:
a@b

array([[ 6, 10, 24],
       [ 6, 12, 24],
       [ 3,  7, 12]])

In [120]:
np.dot(a,b)

array([[ 6, 10, 24],
       [ 6, 12, 24],
       [ 3,  7, 12]])

In [133]:
a=[[[1,2,3],[4,5,6],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]]]

In [137]:
a=np.array(a)
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [138]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 1, 6, 5, 4, 9, 8, 7])

In [141]:
np.expand_dims(a,axis=0)

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 2, 1],
         [6, 5, 4],
         [9, 8, 7]]]])

In [142]:
np.expand_dims(a,axis=1)

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[3, 2, 1],
         [6, 5, 4],
         [9, 8, 7]]]])

In [143]:
np.squeeze(a)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [149]:
a[0][0][0:2]

array([1, 2])

In [162]:
a[0,1:3,1:3]

array([[5, 6],
       [8, 9]])

In [163]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [164]:
a.reshape(6,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [167]:
a.reshape(3,2,3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 2, 1]],

       [[6, 5, 4],
        [9, 8, 7]]])

In [168]:
np.max(a)

9

In [169]:
np.argmax(a)

8

In [170]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [171]:
np.sin(a)

array([[[ 0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ],
        [ 0.6569866 ,  0.98935825,  0.41211849]],

       [[ 0.14112001,  0.90929743,  0.84147098],
        [-0.2794155 , -0.95892427, -0.7568025 ],
        [ 0.41211849,  0.98935825,  0.6569866 ]]])

In [173]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 3, 3, 2, 2,
       1, 1, 6, 6, 5, 5, 4, 4, 9, 9, 8, 8, 7, 7])

In [176]:
np.roll(a,5)

array([[[5, 4, 9],
        [8, 7, 1],
        [2, 3, 4]],

       [[5, 6, 7],
        [8, 9, 3],
        [2, 1, 6]]])

In [177]:
a=np.array([1,2,3,4,5])

In [180]:
np.roll(a,6)

array([5, 1, 2, 3, 4])

In [182]:
np.diag(a)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [185]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [189]:
np.empty(3,int)

array([94511057641821,              0,              0])